spring:
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:file:/Users/eduardo.vieira/Desktop/workspaces/jornada_dev_eficiente/mercadolivre/testdb
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: update