spring:
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:file:/Users/eduardo.vieira/Desktop/workspaces/jornada_dev_eficiente/yfood/testdb
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: create-drop

enderecos-externos:
  valor-pedido: http://localhost:8080/api/pedidos/{idPedido}
  caos-liberado: false
  gateways.base-url: http://localhost:8080

cache:
  usuario-seleciona-restaurante:
    quantidade: 5
    tempo-expiracao: 100